export const BUYER_COLORS = {
  primary: "#004ac6",
  primaryContainer: "#2563eb",
  onPrimary: "#ffffff",
  secondary: "#495c95",
  secondaryContainer: "#acbfff",
  onSecondaryContainer: "#394c84",
  tertiary: "#943700",
  tertiaryContainer: "#bc4800",
  background: "#f9f9ff",
  surface: "#f9f9ff",
  surfaceBright: "#f9f9ff",
  surfaceContainerLowest: "#ffffff",
  surfaceContainerLow: "#f0f3ff",
  surfaceContainer: "#e7eefe",
  surfaceContainerHigh: "#e2e8f8",
  surfaceContainerHighest: "#dce2f3",
  onSurface: "#151c27",
  onSurfaceVariant: "#434655",
  outline: "#737686",
  outlineVariant: "#c3c6d7",
};

export const SELLER_COLORS = {
  primary: "#3525cd",
  primaryContainer: "#4f46e5",
  onPrimary: "#ffffff",
  secondary: "#58579b",
  secondaryContainer: "#b6b4ff",
  onSecondaryContainer: "#454386",
  tertiary: "#7e3000",
  tertiaryContainer: "#a44100",
  background: "#faf8ff",
  surface: "#faf8ff",
  surfaceBright: "#faf8ff",
  surfaceContainerLowest: "#ffffff",
  surfaceContainerLow: "#f2f3ff",
  surfaceContainer: "#eaedff",
  surfaceContainerHigh: "#e2e7ff",
  surfaceContainerHighest: "#dae2fd",
  onSurface: "#131b2e",
  onSurfaceVariant: "#464555",
  outline: "#777587",
  outlineVariant: "#c7c4d8",
};

export const SYSTEM_COLORS = {
  error: "#ba1a1a",               
  errorContainer: "#ffdad6",
  onError: "#ffffff",
  onErrorContainer: "#93000a",
};